name: webhook_api
env:
  PROJECT_NAME: "webhook_api"
  STAGE: "main"
on:
  push:
    branches: [ main ]
jobs:
  deploy_palmershow:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PALMER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY_PALMER }}
          script: |
            cd /home/${{ secrets.USERNAME }}/deploy/${{ env.PROJECT_NAME }}
            git checkout ${{ env.STAGE }}
            git pull
